### DISCUSSION TITLE
How to get a default from completely another part of the tree?

### DISCUSSION THREAD

**Discussion by simon-anz** [colinhacks/zod#3209] [Q&A] [answered]
(probably a noob question)

if I have a structure like:
```yaml
defaults:
  settings:
    color: red
    shape: round
things:
  - name: first_thing
    settings:
      color: blue
      something: else
```

How can I make cfg.things[0].settings.shape return cfg.defaults.settings.shape (if it wasn't provided explicitly)?

This feels kindof like a .default()?  Ideally _all_ of the values in .defaults.settings would be available in .things[0].settings - so a generic "merge"?

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const thingsSchema = z.object( {
    name: z.string(),
    settings: z.object( {
        color: z.string().default( 'red' ),
        shape: z.string().default( 'round' ),
        something: z.string(),
    } ),
} ).array()

type Things = z.infer<typeof thingsSchema>
// type Things = {
//     name: string
//     settings: {
//         color: string
//         shape: string
//         something: string
//     }
// }[]

console.log(
    thingsSchema.parse( [ {
        name: 'first_thing',
        settings: {
            color: 'blue',
            something: 'else',
        },
    } ] )
)
// [
//     {
//       name: "first_thing",
//       settings: {
//         color: "blue",
//         shape: "round",
//         something: "else",
//       },
//     }
// ]
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by simon-anz** [comment]
Sorry, I may have been unclear.  I was giving an example of the document to be parsed against the schema.  I'd like the "default" for the `cfg.things[0].settings.shape` be `cfg.defaults.settings.shape` - rather than any specific value coded into the schema.

**Comment by simon-anz** [comment]
My (actual) schema currently looks like:

```javascript
export default z.object({
    defaults: z.object({
        settings: z.object({
            region: z.string().optional(),
            timezone: z.string().default('utc'),
        }),
    }),

    organizations: z.array(
        z.object({
            accountId: z.number().int(),
            settings: z.object({ region: z.string(), name: z.string() }),
        })
    ).default([]),
```

And I'd like the value for .organizations[*].settings.region to be .defaults.settings.region if it wasn't actually provided in the input document.

**Reply by JacobWeisenburger** [reply]
you would probably need to do that in a [`.transform`](https://github.com/colinhacks/zod#transform)

**Reply by simon-anz** [reply]
how can I access other parts of the "tree" from within a transform (or default) function?

**Reply by JacobWeisenburger** [reply]
when you say "tree", do you mean the schema tree or the value being parsed/validated tree?

**Reply by simon-anz** [reply]
The value tree being parsed.  I've worked around this for now using a Settings type, and a partial, and some javascript:

```javascript
const Settings = z.object({
    region: z.string().optional(),
    timezone: z.string().default('utc'),
});

export default z.object({
    defaults: z.object({
        settings: Settings,
        }),
    }),

    organizations: z.array(
        z.object({
            accountId: z.number().int(),
            settings: z.object({name: z.string()}).merge(Settings.partial()),
        })
    ).default([]),
```

and some code in the caller

```javascript
    const config = ConfigSchema.parse(rawConfig);
    // merge default settings and extract some info
    config.organizations.forEach((org: any) => {
      org.settings = Object.assign({}, config.defaults.settings, org.settings);
    });
```

Which seems to work OK, but feels a bit wrong.  Works with following input:

```yaml
---
defaults:
  settings:
    region: ap-southeast-2
    # timezone: Australia/Melbourne


organizations:
  - accountId: 000000000000
    settings:
      name: some-org-name
      stuff: 123 # ignored
      region: whatever # override default
      # timezone from defaults
```
