### DISCUSSION TITLE
Parametrized values via Zod?

### DISCUSSION THREAD

**Discussion by nehalist** [colinhacks/zod#4400] [Q&A]
Hopefully the title isn't too confusing, but I do have a config that looks like this:

```
params:
  foo: "bar"

config:
  value: "{{params.foo}}"
```

In order to properly validate `config.value` (which must be a string) it would be awesome if I could replace the parameter with its actual value before running validation.

`transform` was my first idea, but afaik I don't have access to other values there.

Anyone got a different idea?

Thanks!
