### ISSUE TITLE
`z.integer()` implicitly uses `MAX_SAFE_INTEGER` to set range, not int32 compatible

### ISSUE THREAD

**Issue by soulchild** [colinhacks/zod#4779]
I'm not sure if this really is a bug. We serve a REST-API whose OpenAPI specification is generated by using zod's `z.toJSONSchema()`. A consumer of this API came back to us complaining about a property having the following specification:

```yaml
ourProperty:
  type: object
  properties:
    anotherProperty:
      type: integer
      minimum: -9007199254740991
      maximum: 9007199254740991
```

The values are obviously based on `Number.MAX_SAFE_INTEGER`. 

The client is using [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate a Java client, which complains about the number range not fitting inside a Java `int`, which is only an `int32`. The [specification](https://swagger.io/docs/specification/v3_0/data-models/data-types/#numbers) says that both integer ranges could have an OpenAPI type of `integer`, but the `format` specifier needs to be set to `int64` if a long integer is used.

I'm not sure whether adding the minimum/maximum values (if not specified) is a good idea in the first place, but I guess that's a similar discussion to whether [regular expressions for known formats should be included](https://github.com/colinhacks/zod/issues/4381) in the spec or not.
